/* No external scripts. All user-controlled text is escaped before rendering. */
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const peso = cents => new Intl.NumberFormat('en-PH', {style:'currency', currency:'PHP'}).format(cents/100);
const today = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const option = (value, name) => `<option value="${esc(value)}">${esc(name)}</option>`;
const field = (label, name, type='text', extra='') => `<label class="field">${label}<input name="${name}" type="${type}" ${extra} required></label>`;
const stat = (label, value) => `<div class="stat"><span>${label}</span><strong>${esc(value)}</strong></div>`;
const empty = cols => `<tr><td class="empty" colspan="${cols}">No records yet. Add one to get started.</td></tr>`;
let toastTimer;
function toast(message, error=false) { const el=$('#toast'); el.textContent=message; el.className=error?'error':''; el.hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.hidden=true,6000); }
async function api(app, path, method='GET', data) {
  const response = await fetch(`/api/${app}${path}`, {method, ...(data===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})});
  const result = await response.json();
  if(!response.ok) throw new Error(result.error || 'Request failed.');
  return result;
}
function bindForm(selector, action) {
  $(selector).addEventListener('submit', async event => {
    event.preventDefault(); const form=event.currentTarget, button=form.querySelector('button[type="submit"]');
    button.disabled=true;
    try { await action(Object.fromEntries(new FormData(form)), form); } catch(error) { toast(error.message,true); }
    finally { button.disabled=false; }
  });
}
function bindAction(selector, action) {
  $(selector).addEventListener('click', async event => { const button=event.target.closest('button'); if(!button) return; button.disabled=true;
    try { await action(button); } catch(error) { toast(error.message,true); } finally { button.disabled=false; }
  });
}
function hero(number, title, description, track) { return `<header class="hero hero-row"><div><div class="eyebrow">Project ${number} / ${track}</div><h1>${title}</h1><p>${description}</p></div><span class="badge">Working local demo</span></header>`; }
const collection = [
  ['smartfind','01','SmartFind','Web development','A searchable stock dashboard with inventory validation and a complete stock-movement history.'],
  ['attendance','02','AttendFlow','Backend engineering','A relational attendance API with event reports, duplicate protection and CSV exports.'],
  ['peso','03','PesoLens','Data & analytics','Turn expense records into monthly insights. Import CSVs, compare categories and export clean data.'],
  ['accesspath','04','AccessPath','Algorithms','Find a route that respects stairs, slopes, path width and closures on a fictional campus.'],
  ['minilang','05','MiniLang','Language tooling','Write a tiny program, inspect its tokens and syntax tree, then run a bounded interpreter.']
];
function home() {
  $('#view').innerHTML=`<header class="hero"><div class="eyebrow">The portfolio collection / 2026</div><h1>Find your direction.<br>Build something real.</h1><p>A hands-on collection for exploring computer science roles. Open a project, try its workflow, then read the code behind it.</p></header><div class="section-label"><span>FIVE PROJECTS TO EXPLORE</span><span>All demo data is synthetic</span></div><div class="grid">${collection.map(([id,num,title,track,desc],i)=>`<article class="card ${i===0?'featured':''}"><div class="card-number"><span>${num} / 05</span><span>${track}</span></div><h2>${title}</h2><p>${desc}</p><a href="/?app=${id}">Explore project <span aria-hidden="true">↗</span></a></article>`).join('')}<article class="card path-card"><div class="card-number"><span>YOUR NEXT STEP</span></div><h2>You can choose later.</h2><p>Rate each project for enjoyment, curiosity and confidence after making your own improvement. Start with the one you want to return to.</p><span class="badge">Try → improve → explain</span></article></div><p class="footer">Built as learning MVPs. Run locally, use synthetic data, and read each project's limitations before extending it.</p>`;
}
async function smartfind() {
  $('#view').innerHTML=hero('01','Stock, without the guesswork.','Search a school-supplies inventory, record changes and spot products that need restocking.','Web development')+`<div class="stats" id="stats"></div><div class="split"><section class="panel"><div class="toolbar"><h2>Product inventory</h2><input id="search" type="search" aria-label="Search products" placeholder="Search name, SKU or category"></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th></tr></thead><tbody id="products"></tbody></table></div></section><div><section class="panel"><h2>Add a product</h2><form id="add-product">${field('Product name','name','text','maxlength="120"')}${field('SKU','sku','text','maxlength="30"')}${field('Category','category','text','maxlength="40"')}<div class="field-row">${field('Price (PHP)','price','number','min="0" max="1000000" step="0.01"')}${field('Opening stock','stock','number','min="0" max="1000000" step="1"')}</div>${field('Reorder level','reorder_level','number','min="0" max="1000000" value="5"')}<button type="submit">Add product</button></form></section><section class="panel"><h2>Adjust stock</h2><form id="adjust-stock"><label class="field">Product<select name="product_id" id="product-select" required></select></label>${field('Change (+ incoming, − outgoing)','delta','number','min="-1000000" max="1000000" step="1"')}${field('Reason','reason','text','maxlength="200"')}<button type="submit">Record adjustment</button></form></section></div></div><section class="panel below"><h2>Recent stock movements</h2><div id="movements" class="ledger"></div></section>`;
  let products=[];
  function render() { const term=$('#search').value.toLowerCase(); $('#products').innerHTML=products.filter(p=>`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(term)).map(p=>`<tr><td><strong>${esc(p.name)}</strong><small>${esc(p.sku)} · ${esc(p.category)}</small></td><td>${peso(p.price_cents)}</td><td>${p.stock}</td><td><span class="tag ${p.stock===0?'bad':p.low_stock?'warning':''}">${p.stock===0?'Out of stock':p.low_stock?'Low stock':'Available'}</span></td></tr>`).join('')||empty(4); }
  async function refresh() { const [items,movements]=await Promise.all([api('smartfind','/products'),api('smartfind','/movements')]); products=items; render(); $('#product-select').innerHTML=products.map(p=>option(p.id,p.name)).join(''); $('#stats').innerHTML=stat('Products',products.length)+stat('Low / empty stock',products.filter(p=>p.low_stock).length)+stat('Inventory value',peso(products.reduce((sum,p)=>sum+p.price_cents*p.stock,0))); $('#movements').innerHTML=movements.map(m=>`<div class="ledger-entry"><span>${m.delta>0?'+':''}${m.delta} units</span>${esc(m.name)}<small>${esc(m.reason)} · ${esc(m.created_at)} UTC</small></div>`).join(''); }
  $('#search').addEventListener('input',render);
  bindForm('#add-product',async(d,f)=>{ await api('smartfind','/products','POST',{...d,stock:Number(d.stock),reorder_level:Number(d.reorder_level)}); f.reset(); await refresh(); toast('Product added.'); });
  bindForm('#adjust-stock',async(d,f)=>{ await api('smartfind','/adjust','POST',{...d,product_id:Number(d.product_id),delta:Number(d.delta)}); f.reset(); await refresh(); toast('Stock adjustment recorded.'); });
  await refresh();
}
async function attendance() {
  $('#view').innerHTML=hero('02','Every check-in accounted for.','Manage workshop attendance with one record per student and event. Reports include students who are absent.','Backend engineering')+`<div class="stats" id="stats"></div><div class="split"><section class="panel"><div class="toolbar"><select id="event-select" aria-label="Choose event"></select><a id="export" class="button secondary">Export CSV</a></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Status</th><th>Time (local)</th><th>Action</th></tr></thead><tbody id="records"></tbody></table></div></section><div><section class="panel"><h2>Add student</h2><form id="student-form">${field('Student number','student_no','text','maxlength="30"')}${field('Full name','name','text','maxlength="120"')}${field('Course','course','text','maxlength="80" value="BS Computer Science"')}<button type="submit">Add student</button></form></section><section class="panel"><h2>Create event</h2><form id="event-form">${field('Event name','name','text','maxlength="120"')}${field('Event date','event_date','date')}<button type="submit">Create event</button></form></section></div></div><p class="footer">Demonstration attendance. Dates describe events; check-ins use the current time and are stored in UTC.</p>`;
  $('#event-form [name="event_date"]').value=today();
  async function records() { const event=$('#event-select').value; const list=await api('attendance',`/records?event_id=${event}`); $('#export').href=`/api/attendance/export?event_id=${event}`; $('#export').download='attendance.csv'; $('#stats').innerHTML=stat('Registered students',list.length)+stat('Checked in',list.filter(r=>r.time_in).length)+stat('Completed',list.filter(r=>r.time_out).length); $('#records').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.name)}</strong><small>${esc(r.student_no)}</small></td><td><span class="tag ${r.status==='Absent'?'warning':''}">${r.status}</span></td><td>${r.time_in?esc(new Date(r.time_in).toLocaleTimeString()):'—'}${r.time_out?`<br><small>Out ${esc(new Date(r.time_out).toLocaleTimeString())}</small>`:''}</td><td>${r.status==='Completed'?'Done':`<button class="small ${r.status==='Present'?'secondary':''}" data-student="${r.student_id}" data-action="${r.status==='Absent'?'check-in':'check-out'}">${r.status==='Absent'?'Check in':'Check out'}</button>`}</td></tr>`).join('')||empty(4); }
  async function events(selected) { const list=await api('attendance','/events'); const current=selected||$('#event-select').value; $('#event-select').innerHTML=list.map(e=>option(e.id,`${e.name} · ${e.event_date}`)).join(''); if(current) $('#event-select').value=current; await records(); }
  $('#event-select').addEventListener('change',()=>records().catch(e=>toast(e.message,true)));
  bindAction('#records',async b=>{ await api('attendance',`/${b.dataset.action}`,'POST',{student_id:Number(b.dataset.student),event_id:Number($('#event-select').value)}); await records(); toast('Attendance updated.'); });
  bindForm('#student-form',async(d,f)=>{ await api('attendance','/students','POST',d); f.reset(); await records(); toast('Student added.'); });
  bindForm('#event-form',async(d,f)=>{ const result=await api('attendance','/events','POST',d); f.reset(); f.elements.event_date.value=today(); await events(String(result.id)); toast('Event created.'); });
  await events();
}
async function pesoLens() {
  $('#view').innerHTML=hero('03','See where your pesos go.','Explore monthly income and expenses, compare spending categories and import your own CSV records.','Data & analytics')+`<div class="toolbar"><label class="field">Reporting month<input type="month" id="month" required></label><a id="export" class="button secondary">Export month CSV</a></div><div class="stats" id="stats"></div><div class="split"><div><section class="panel"><h2>Spending by category</h2><div id="categories" class="bars"></div></section><section class="panel"><h2>Transaction history</h2><div class="table-wrap"><table><thead><tr><th>Details</th><th>Date</th><th>Amount</th><th>Action</th></tr></thead><tbody id="transactions"></tbody></table></div></section></div><div><section class="panel"><h2>Add transaction</h2><form id="transaction-form"><label class="field">Type<select name="kind">${option('expense','Expense')}${option('income','Income')}</select></label>${field('Category','category','text','maxlength="50"')}${field('Amount (PHP)','amount','number','min="0.01" max="1000000" step="0.01"')}${field('Date','date','date')}<label class="field">Note (optional)<input name="note" maxlength="300"></label><button type="submit">Add transaction</button></form></section><section class="panel"><h2>Import a CSV</h2><p>Columns: kind, category, amount, date, note. All rows are validated before any are saved.</p><form id="import-form"><label class="field">CSV file<input type="file" name="file" accept=".csv,text/csv" required></label><button type="submit" class="secondary">Import transactions</button></form><p class="hint">Imports append rows. Importing the same file again creates duplicates.</p></section></div></div>`;
  $('#month').value=today().slice(0,7); $('#transaction-form [name="date"]').value=today();
  async function refresh() { const month=$('#month').value; if(!month) return; const [summary,list]=await Promise.all([api('peso',`/summary?month=${month}`),api('peso',`/transactions?month=${month}`)]); $('#stats').innerHTML=stat('Income',peso(summary.income))+stat('Expenses',peso(summary.expense))+stat('Balance',peso(summary.balance)); $('#export').href=`/api/peso/export?month=${month}`; $('#export').download=`expenses-${month}.csv`; $('#categories').innerHTML=summary.categories.map(c=>`<div><div class="bar-label"><span>${esc(c.category)}</span><span>${peso(c.total)} · ${Math.round(c.total/summary.expense*100)}%</span></div><svg class="bar-svg" viewBox="0 0 100 9" preserveAspectRatio="none" aria-hidden="true"><rect width="100" height="9" rx="4" fill="#eef2e5"/><rect width="${c.total/summary.expense*100}" height="9" rx="4" fill="#587b48"/></svg></div>`).join('')||'<p class="empty">No expenses in this month.</p>'; $('#transactions').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.category)}</strong><small>${esc(r.note)} · ${r.kind}</small></td><td>${r.transaction_date}</td><td>${r.kind==='expense'?'−':'+'}${peso(r.amount_cents)}</td><td><button class="small danger" data-id="${r.id}" aria-label="Delete ${esc(r.category)} transaction">Delete</button></td></tr>`).join('')||empty(4); }
  $('#month').addEventListener('change',()=>refresh().catch(e=>toast(e.message,true)));
  bindForm('#transaction-form',async(d,f)=>{ await api('peso','/transactions','POST',d); $('#month').value=d.date.slice(0,7); f.reset(); f.elements.date.value=today(); await refresh(); toast('Transaction added.'); });
  bindAction('#transactions',async b=>{ if(!confirm('Delete this transaction?')) return; await api('peso',`/transactions/${b.dataset.id}`,'DELETE',{}); await refresh(); toast('Transaction deleted.'); });
  bindForm('#import-form',async(d,f)=>{ const file=f.elements.file.files[0]; if(file.size>100000) throw new Error('Choose a CSV smaller than 100 KB.'); const result=await api('peso','/import','POST',{csv:await file.text()}); await refresh(); toast(`${result.imported} transactions imported. Select their month to view them.`); f.reset(); });
  await refresh();
}
async function accesspath() {
  $('#view').innerHTML=hero('04','A path that fits your needs.','Compare the shortest route with a route that respects your mobility preferences.','Algorithms')+`<div class="notice">Fictional campus and unverified demo measurements. This is an algorithm demonstration, not real-world navigation guidance.</div><div class="split"><div><section class="panel"><h2>Campus route explorer</h2><svg id="map" class="map" viewBox="0 0 710 420" role="img" aria-label="Fictional campus paths with the planned route highlighted"></svg><p class="hint">Green = chosen route · Dashed = stairs · Red dotted = closed</p><div id="route-result" class="route-result" aria-live="polite">Choose your preferences, then plan a route.</div></section><section class="panel"><h2>Path conditions</h2><div id="segments" class="segments"></div></section></div><section class="panel"><h2>Your route preferences</h2><form id="route-form"><label class="field">Start<select name="start" id="start"></select></label><label class="field">Destination<select name="end" id="end"></select></label><label class="check"><input type="checkbox" name="step_free" checked> Avoid stairs</label>${field('Maximum slope (%)','max_slope','number','min="0" max="20" step="0.5" value="8"')}${field('Minimum path width (cm)','min_width','number','min="50" max="250" value="90"')}<button type="submit">Plan route</button></form><p>Close a segment below the map to test rerouting. Constraints are preferences, not accessibility certifications.</p></section></div>`;
  let map, chosen=[];
  function draw() { const nodes=Object.fromEntries(map.nodes.map(n=>[n.id,n])); $('#map').innerHTML=`<title>Fictional campus route</title>${map.edges.map(e=>{ const a=nodes[e.a],b=nodes[e.b]; return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="${e.stairs?'stairs ':''}${e.blocked?'blocked ':''}${chosen.includes(e.id)?'route':''}"><title>${esc(a.name)} to ${esc(b.name)}: ${e.distance} m</title></line>`; }).join('')}${map.nodes.map(n=>`<g><circle cx="${n.x}" cy="${n.y}" r="10"/><text x="${n.x}" y="${n.y-20}" text-anchor="middle">${esc(n.name)}</text></g>`).join('')}`; $('#segments').innerHTML=map.edges.map(e=>`<div class="segment"><div>${esc(nodes[e.a].name)} ↔ ${esc(nodes[e.b].name)}<small>${e.distance} m · ${e.slope}% slope · ${e.width} cm wide${e.stairs?' · Stairs':''}</small></div><button class="small ${e.blocked?'danger':'secondary'}" data-id="${e.id}" data-blocked="${e.blocked}">${e.blocked?'Reopen':'Close path'}</button></div>`).join(''); }
  async function refresh() { map=await api('accesspath','/map'); draw(); }
  bindForm('#route-form',async d=>{ const result=await api('accesspath','/plan','POST',{start:d.start,end:d.end,step_free:d.step_free==='on',max_slope:Number(d.max_slope),min_width:Number(d.min_width)}); chosen=result.edges; draw(); const names=Object.fromEntries(map.nodes.map(n=>[n.id,n.name])); $('#route-result').innerHTML=result.found?`<strong>${result.distance} metres</strong>${result.nodes.map(n=>esc(names[n])).join(' → ')}<p>${result.excluded.length} segments excluded by your preferences or closures.</p>`:'<strong>No route available</strong>Try different preferences or reopen a path. Your constraints were respected.'; });
  bindAction('#segments',async b=>{ await api('accesspath',`/edges/${b.dataset.id}`,'PATCH',{blocked:b.dataset.blocked==='0'}); chosen=[]; await refresh(); $('#route-result').textContent='Path conditions changed. Plan again to refresh your route.'; toast('Path condition updated.'); });
  await refresh(); $('#start').innerHTML=map.nodes.map(n=>option(n.id,n.name)).join(''); $('#end').innerHTML=$('#start').innerHTML; $('#start').value='gate'; $('#end').value='lab';
}
async function minilang() {
  $('#view').innerHTML=hero('05','A small language. A clear pipeline.','Follow your source code from tokens to a syntax tree to execution, with useful errors at each step.','Language tooling')+`<div class="split"><section class="panel"><div class="toolbar"><h2>Program editor</h2><button id="example" class="secondary">Load example</button></div><form id="code-form"><label class="field" for="source">MiniLang source</label><textarea id="source" name="source" class="editor" maxlength="4000" spellcheck="false" required></textarea><div class="toolbar below"><span class="hint">let · print · repeat · arithmetic</span><button type="submit">Run program</button></div></form><p class="hint">Statements end with semicolons. Repeat uses braces. # begins a comment. Values are numeric; variables share one global scope.</p></section><section class="panel"><h2>Inspect the result</h2><div class="tabs" aria-label="Result view"><button class="secondary active" data-tab="output" aria-pressed="true">Output</button><button class="secondary" data-tab="tokens" aria-pressed="false">Tokens</button><button class="secondary" data-tab="ast" aria-pressed="false">AST</button></div><pre id="result" class="code-output" aria-live="polite">Run a program to see its output.</pre><div id="execution" class="hint"></div></section></div><div class="notice below">Execution stays within the interpreter. Programs have no file, network or Python access. Loops and output are bounded.</div>`;
  const example='# A simple running total\nlet total = 0;\nlet step = 3;\nrepeat 4 {\n  let total = total + step;\n  print total;\n}\nprint (total + 2) * 5;';
  $('#source').value=example; let result=null, tab='output';
  function render() { if(!result) return; $('#result').textContent=tab==='output'?(result.output.join('\n')||'(No output)'):JSON.stringify(result[tab],null,2); }
  $('#example').addEventListener('click',()=>{$('#source').value=example;});
  bindAction('.tabs',async b=>{ tab=b.dataset.tab; document.querySelectorAll('.tabs button').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));}); render(); });
  bindForm('#code-form',async d=>{ result=null; $('#execution').textContent=''; try { result=await api('minilang','/run','POST',d); render(); $('#execution').textContent=`${result.tokens.length} tokens · ${result.steps} execution steps · Variables: ${JSON.stringify(result.variables)}`; } catch(e) { $('#result').textContent=e.message; throw e; } });
}
const app=new URLSearchParams(location.search).get('app')||'home';
document.querySelector(`nav a[data-app="${collection.some(c=>c[0]===app)?app:'home'}"]`)?.classList.add('active');
const pages={home,smartfind,attendance,peso:pesoLens,accesspath,minilang};
Promise.resolve().then(()=> (pages[app]||home)()).catch(error=>{toast(error.message,true); console.error(error);});
